application: final-proj-1270
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /style
  static_dir: style

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /.*
  script: main.app


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
